const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "null"
const SESSION_ID = "PRABATH-MD~g2NUgTYT#rREaFhm9aJ17uLCF_rIzmdPuHsCA8D8MikCOfD3YoaQ"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
